version: '3.7'
services:
  api:
    image: dapr-awesomeapi
    container_name: awesome_api
    ports:
      - "3333:3333"

  process:
    image: dapr-awesomeprocess
    container_name: awesome_process
    ports:
      - "3331:3333"

  api_dapr:
    image: daprio/dapr:1.6.0
    command:
      [
        "./daprd",
        "-app-id",
        "api",
        "-app-port",
        "3333",
        "-components-path",
        "/dapr/local"
      ]
    volumes:
      - "./components:/dapr"
    depends_on:
      - api
    network_mode: "service:api"

  process_dapr:
    image: daprio/dapr:1.6.0
    command:
      [
        "./daprd",
        "-app-id",
        "process",
        "-app-port",
        "3333",
        "-components-path",
        "/dapr/local"
      ]
    volumes:
      - "./components:/dapr"
    depends_on:
      - process
    network_mode: "service:process"
networks:
  default:
    external:
      name: dapr_network
